//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCFBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_bpkb
    {
        public string agreement_number { get; set; }
        public string bpkb_no { get; set; }
        public string branch_id { get; set; }
        public System.DateTime bpkb_date { get; set; }
        public string faktur_no { get; set; }
        public System.DateTime faktur_date { get; set; }
        public string location_id { get; set; }
        public string police_no { get; set; }
        public System.DateTime bpkb_date_in { get; set; }
    
        public virtual ms_storage_location ms_storage_location { get; set; }
    }
}
